# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de759a3e5e0c19d285beff7778ea2f8173f764ad325610f7c15f1a506f586f948556d88f5a32da382f23db7a1c4ca06cb0cef60a3e3155c48ef4c8ffcfba6525

test:
  secret_key_base: 6017d81d0b06b5d26457a924bc78971424bc9ac979fcba2abbf4d9c3374e8adfe5bd107051df88b5540fbbc5bb7f34578bacc46e1bbd5c98de48dcd42007671e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
